### PR TITLE
ci: added ci builds, tests, and deploys

### LINKED ISSUE #15: Set up automated builds with Github actions
Every PR should be built and tested by Github actions.
Possibly an upload as well?

### PR DESCRIPTION
**Pull request by Mastermindzh**
This PR adds ci builds using Github actions.
Two of the steps are disabled:

- Deploy step, it needs secrets set up on the maintainer's part (see: [documentation](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)
- Tests, as described in issue #17, tests are currently not quite portable enough for me to set up in CI

fixes #15

### CODE REVIEW

**Comment by pascal89** [comment]
Nice. I think the test project can be converted to be able to run it in the pipeline. Have a look at this PR: https://github.com/growthbook/growthbook-c-sharp/pull/13 ;-)

**Comment by Mastermindzh** [comment]
Oh I agree, just didn't have the time to do it (read: didn't want to invest more at the time) 😄.
Are you waiting on it to do your IGrowthBook tests?

**Comment by darklordzw** [comment]
@pascal89, [PR #13](https://github.com/growthbook/growthbook-c-sharp/pull/13) has been merged into main.

**Comment by Mastermindzh** [comment]
I'll fix this after eating 😄 , Thanks for merging #13

**Comment by Mastermindzh** [comment]
@darklordzw, 

Let me know how you want to do this merge. I got all the tests moved over to XUnit.

You can see the PR here: https://github.com/Inforitnl/growthbook-c-sharp/pull/1
You can see the test results here: https://github.com/Inforitnl/growthbook-c-sharp/actions/runs/6698308487/job/18200066562?pr=1
And on this picture:
image


We can go 1 of 2 ways:

1. I can merge the PR#1 on our INFORIT branch, which will update this PR
2. You can merge this PR and then I will make a new one that will enable tests.

Just let me know and I'll make it happen 😄.

This will fix #17

**Review by pascal89 — APPROVED** [review]

**Comment by darklordzw** [comment]
@Mastermindzh, option #2 sounds good. I've merged this PR into main. Once the tests are ready, I'll update the secrets for the deploy step.

Thanks again for all your help!

**Comment by Mastermindzh** [comment]
No problem @darklordzw 😄.

Things were taking a while at our side so I decided to just do some stuff over the weekends/evenings to get the ball rolling.
Thanks for being so quick with reviews & merges.

**Pull request merged**
